packages:
  - docs
  - packages/*

overrides:
  '@docsearch/react': '-'
  rolldown: catalog:prod
  vite: catalog:docs

catalogs:
  create:
    '@clack/prompts': ^1.3.0
    giget: ^3.2.0
  dev:
    '@sxzz/eslint-config': ^8.0.0
    '@sxzz/prettier-config': ^2.3.1
    '@sxzz/test-utils': ^0.5.18
    '@types/node': ^25.6.0
    '@types/picomatch': ^4.0.3
    '@types/semver': ^7.7.1
    '@typescript/native-preview': 7.0.0-dev.20260501.1
    '@vitest/coverage-v8': ^4.1.5
    '@vitest/ui': ^4.1.5
    baseline-browser-mapping: ^2.10.24
    bumpp: ^11.0.1
    dedent: ^1.7.2
    eslint: ^10.2.1
    memfs: ^4.57.2
    pkg-types: ^2.3.1
    postcss: ^8.5.13
    postcss-import: ^16.1.1
    prettier: ^3.8.3
    rolldown-plugin-require-cjs: ^0.4.0
    sass: ^1.99.0
    tsnapi: ^0.3.2
    tsx: ^4.21.0
    typescript: ~6.0.3
    unplugin-ast: ^0.16.0
    unplugin-raw: ^0.7.0
    unplugin-vue: ^7.2.0
    unrun: ^0.2.37
    vitest: ^4.1.5
  docs:
    '@iconify-json/logos': ^1.2.11
    '@shikijs/vitepress-twoslash': ^4.0.2
    '@unocss/eslint-plugin': ^66.6.8
    '@vueuse/core': ^14.3.0
    oxc-minify: ^0.128.0
    typedoc: ^0.28.19
    typedoc-plugin-markdown: ^4.11.0
    typedoc-vitepress-theme: ^1.1.2
    unocss: ^66.6.8
    vite: ^8.0.10
    vitepress: ^2.0.0-alpha.17
    vitepress-plugin-group-icons: ^1.7.5
    vitepress-plugin-llms: ^1.12.1
    vue: ^3.5.33
    vue-tsc: ^3.2.7
  migrate:
    '@antfu/ni': ^30.1.0
    '@ast-grep/napi': ^0.42.1
    consola: ^3.4.2
    diff: ^9.0.0
  peer:
    '@arethetypeswrong/core': ^0.18.2
    '@vitejs/devtools': ^0.1.17
    publint: ^0.3.18
    unplugin-unused: ^0.5.7
  prod:
    ansis: ^4.2.0
    cac: ^7.0.0
    defu: ^6.1.7
    empathic: ^2.0.0
    hookable: ^6.1.1
    import-without-cache: ^0.3.3
    is-in-ci: ^2.0.0
    lightningcss: ^1.32.0
    obug: ^2.1.1
    package-manager-detector: ^1.6.0
    picomatch: ^4.0.4
    postcss-load-config: ^6.0.1
    rolldown: 1.0.0-rc.18
    rolldown-plugin-dts: ^0.24.0
    semver: ^7.7.4
    tinyexec: ^1.1.2
    tinyglobby: ^0.2.16
    tree-kill: ^1.2.2
    unconfig-core: ^7.5.0

allowBuilds:
  '@parcel/watcher': false
  esbuild: false

ignoreWorkspaceRootCheck: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 7 days
