catalogs:
  dev:
    '@oxc-node/core': ^0.0.27
    '@sxzz/eslint-config': ^7.0.1
    '@sxzz/prettier-config': ^2.2.1
    '@sxzz/test-utils': ^0.5.6
    '@types/debug': ^4.1.12
    '@types/node': ^22.15.19
    '@types/semver': ^7.7.0
    bumpp: ^10.1.1
    eslint: ^9.27.0
    lightningcss: ^1.30.1
    pkg-types: ^2.1.0
    prettier: ^3.5.3
    publint: ^0.3.12
    tsup: ^8.5.0
    typescript: ~5.8.3
    unplugin-lightningcss: ^0.4.0
    unplugin-unused: ^0.5.0
    vitest: ^3.1.3

  docs:
    '@unocss/eslint-plugin': ^66.1.2
    typedoc: ^0.28.4
    typedoc-plugin-markdown: ^4.6.3
    unocss: ^66.1.2
    vite: ^6.3.5
    vitepress: ^1.6.3
    vitepress-plugin-group-icons: ^1.5.5
    vitepress-plugin-llms: ^1.3.2
    vue: ^3.5.14

  prod:
    ansis: ^4.0.0
    cac: ^6.7.14
    chokidar: ^4.0.3
    debug: ^4.4.1
    diff: ^8.0.1
    empathic: ^1.1.0
    hookable: ^5.5.3
    rolldown: 1.0.0-beta.9
    rolldown-plugin-dts: ^0.13.2
    semver: ^7.7.2
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.13
    unconfig: ^7.3.2

ignoredBuiltDependencies:
  - rolldown
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
