packages:
  - docs
  - packages/*

overrides:
  rolldown: 'catalog:prod'
  vite: 'catalog:docs'

catalogs:
  dev:
    '@arethetypeswrong/core': ^0.18.2
    '@sxzz/eslint-config': ^7.2.7
    '@sxzz/prettier-config': ^2.2.4
    '@sxzz/test-utils': ^0.5.12
    '@types/debug': ^4.1.12
    '@types/node': ^24.9.1
    '@types/semver': ^7.7.1
    bumpp: ^10.3.1
    eslint: ^9.38.0
    lightningcss: ^1.30.2
    pkg-types: ^2.3.0
    prettier: ^3.6.2
    publint: ^0.3.15
    rolldown-plugin-require-cjs: ^0.3.1
    typescript: ~5.9.3
    unplugin-lightningcss: ^0.4.3
    unplugin-unused: ^0.5.4
    unrun: ^0.2.1
    vitest: ^4.0.3

  docs:
    '@shikijs/vitepress-twoslash': ^3.14.0
    '@unocss/eslint-plugin': ^66.5.4
    '@vueuse/core': ^14.0.0
    oxc-minify: ^0.95.0
    typedoc: ^0.28.14
    typedoc-plugin-markdown: ^4.9.0
    typedoc-vitepress-theme: ^1.1.2
    unocss: ^66.5.4
    vite: npm:rolldown-vite@latest
    vitepress: ^2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.5
    vitepress-plugin-llms: ^1.8.1
    vue: ^3.5.22
    vue-tsc: ^3.1.2

  prod:
    '@clack/prompts': ^0.11.0
    ansis: ^4.2.0
    cac: ^6.7.14
    chokidar: ^4.0.3
    debug: ^4.4.3
    diff: ^8.0.2
    empathic: ^2.0.0
    giget: ^2.0.0
    hookable: ^5.5.3
    package-manager-detector: ^1.5.0
    rolldown: 1.0.0-beta.45
    rolldown-plugin-dts: ^0.17.1
    semver: ^7.7.3
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.15
    tree-kill: ^1.2.2
    unconfig: ^7.3.3

ignoredBuiltDependencies:
  - rolldown
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
