packages:
  - docs

overrides:
  rolldown: 'catalog:prod'
  vite: 'catalog:docs'

catalogs:
  dev:
    '@arethetypeswrong/core': ^0.18.2
    '@sxzz/eslint-config': ^7.2.5
    '@sxzz/prettier-config': ^2.2.4
    '@sxzz/test-utils': ^0.5.11
    '@types/debug': ^4.1.12
    '@types/node': ^24.5.2
    '@types/semver': ^7.7.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    lightningcss: ^1.30.1
    pkg-types: ^2.3.0
    prettier: ^3.6.2
    publint: ^0.3.13
    rolldown-plugin-require-cjs: ^0.1.5
    tsx: ^4.20.5
    typescript: ~5.9.2
    unplugin-lightningcss: ^0.4.3
    unplugin-unused: ^0.5.3
    vitest: ^3.2.4

  docs:
    '@unocss/eslint-plugin': ^66.5.2
    '@vueuse/core': ^13.9.0
    oxc-minify: ^0.92.0
    typedoc: ^0.28.13
    typedoc-plugin-markdown: ^4.9.0
    typedoc-vitepress-theme: ^1.1.2
    unocss: ^66.5.2
    vite: npm:rolldown-vite@latest
    vitepress: ^2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.3
    vitepress-plugin-llms: ^1.7.5
    vue: ^3.5.22
    vue-tsc: ^3.0.8

  prod:
    ansis: ^4.1.0
    cac: ^6.7.14
    chokidar: ^4.0.3
    debug: ^4.4.3
    diff: ^8.0.2
    empathic: ^2.0.0
    hookable: ^5.5.3
    rolldown: latest
    rolldown-plugin-dts: ^0.16.8
    semver: ^7.7.2
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.15
    tree-kill: ^1.2.2
    unconfig: ^7.3.3

ignoredBuiltDependencies:
  - rolldown
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
