packages:
  - docs
  - packages/*

overrides:
  '@docsearch/react': '-'
  rolldown: catalog:prod
  vite: catalog:docs

catalogs:
  create:
    '@clack/prompts': ^1.0.0
    giget: ^3.1.1
  dev:
    '@publint/pack': ^0.1.3
    '@sxzz/eslint-config': ^7.6.0
    '@sxzz/prettier-config': ^2.3.1
    '@sxzz/test-utils': ^0.5.15
    '@types/node': ^25.2.0
    '@types/picomatch': ^4.0.2
    '@types/semver': ^7.7.1
    '@typescript/native-preview': 7.0.0-dev.20260203.1
    '@vitest/coverage-v8': ^4.0.18
    '@vitest/ui': ^4.0.18
    bumpp: ^10.4.0
    dedent: ^1.7.1
    eslint: ^9.39.2
    lightningcss: ^1.31.1
    memfs: ^4.56.10
    pkg-types: ^2.3.0
    prettier: ^3.8.1
    rolldown-plugin-dts-snapshot: ^0.3.2
    rolldown-plugin-require-cjs: ^0.3.3
    typescript: ~5.9.3
    unplugin-ast: ^0.16.0
    vitest: ^4.0.18
  docs:
    '@iconify-json/logos': ^1.2.10
    '@shikijs/vitepress-twoslash': ^3.22.0
    '@unocss/eslint-plugin': ^66.6.0
    '@vueuse/core': ^14.2.0
    oxc-minify: ^0.112.0
    typedoc: ^0.28.16
    typedoc-plugin-markdown: ^4.9.0
    typedoc-vitepress-theme: ^1.1.2
    unocss: ^66.6.0
    vite: ^8.0.0-beta.12
    vitepress: ^2.0.0-alpha.16
    vitepress-plugin-group-icons: ^1.7.1
    vitepress-plugin-llms: ^1.10.0
    vue: ^3.5.27
    vue-tsc: ^3.2.4
  migrate:
    '@antfu/ni': ^28.2.0
    '@ast-grep/napi': ^0.40.5
    consola: ^3.4.2
    diff: ^8.0.3
  peer:
    '@arethetypeswrong/core': ^0.18.2
    '@vitejs/devtools': ^0.0.0-alpha.26
    publint: ^0.3.17
    unplugin-lightningcss: ^0.4.5
    unplugin-unused: ^0.5.7
  prod:
    ansis: ^4.2.0
    cac: ^6.7.14
    defu: ^6.1.4
    empathic: ^2.0.0
    hookable: ^6.0.1
    import-without-cache: ^0.2.5
    is-in-ci: ^2.0.0
    obug: ^2.1.1
    package-manager-detector: ^1.6.0
    picomatch: ^4.0.3
    rolldown: 1.0.0-rc.2
    rolldown-plugin-dts: ^0.21.9
    semver: ^7.7.3
    tinyexec: ^1.0.2
    tinyglobby: ^0.2.15
    tree-kill: ^1.2.2
    unconfig-core: ^7.4.2
    unrun: ^0.2.26

ignoreWorkspaceRootCheck: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - memfs@4.56.2
