packages:
  - docs
  - packages/*

overrides:
  rolldown: catalog:prod
  vite: catalog:docs

catalogs:
  create:
    '@clack/prompts': ^0.11.0
    giget: ^2.0.0
  dev:
    '@sxzz/eslint-config': ^7.4.3
    '@sxzz/prettier-config': ^2.2.6
    '@sxzz/test-utils': ^0.5.14
    '@types/node': ^25.0.2
    '@types/picomatch': ^4.0.2
    '@types/semver': ^7.7.1
    '@typescript/native-preview': 7.0.0-dev.20251216.1
    '@vitest/coverage-v8': 4.0.15
    '@vitest/ui': ^4.0.15
    bumpp: ^10.3.2
    dedent: ^1.7.0
    eslint: ^9.39.2
    lightningcss: ^1.30.2
    memfs: ^4.51.1
    pkg-types: ^2.3.0
    prettier: ^3.7.4
    rolldown-plugin-require-cjs: ^0.3.3
    typescript: ~5.9.3
    vitest: ^4.0.15
  docs:
    '@shikijs/vitepress-twoslash': ^3.20.0
    '@unocss/eslint-plugin': ^66.5.10
    '@vueuse/core': ^14.1.0
    oxc-minify: ^0.103.0
    typedoc: ^0.28.15
    typedoc-plugin-markdown: ^4.9.0
    typedoc-vitepress-theme: ^1.1.2
    unocss: ^66.5.10
    vite: ^8.0.0-beta.2
    vitepress: ^2.0.0-alpha.15
    vitepress-plugin-group-icons: ^1.6.5
    vitepress-plugin-llms: ^1.9.3
    vue: ^3.5.25
    vue-tsc: ^3.1.8
  migrate:
    '@antfu/ni': ^28.0.0
    '@ast-grep/napi': ^0.40.3
    consola: ^3.4.2
    diff: ^8.0.2
  peer:
    '@arethetypeswrong/core': ^0.18.2
    '@vitejs/devtools': ^0.0.0-alpha.20
    publint: ^0.3.16
    unplugin-lightningcss: ^0.4.3
    unplugin-unused: ^0.5.6
  prod:
    ansis: ^4.2.0
    cac: ^6.7.14
    defu: ^6.1.4
    empathic: ^2.0.0
    hookable: ^5.5.3
    import-without-cache: ^0.2.4
    is-in-ci: ^2.0.0
    obug: ^2.1.1
    package-manager-detector: ^1.6.0
    picomatch: ^4.0.3
    rolldown: 1.0.0-beta.53
    rolldown-plugin-dts: ^0.18.3
    semver: ^7.7.3
    tinyexec: ^1.0.2
    tinyglobby: ^0.2.15
    tree-kill: ^1.2.2
    unconfig-core: ^7.4.2
    unrun: ^0.2.19

ignoreWorkspaceRootCheck: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
