/**
 * Generated by tsnapi — public API snapshot of `tsdown/config`
 */
// #region Interfaces
export interface UserConfig {
  entry?: TsdownInputOption;
  deps?: DepsConfig;
  external?: DepsConfig["neverBundle"];
  noExternal?: DepsConfig["alwaysBundle"];
  inlineOnly?: DepsConfig["onlyBundle"];
  skipNodeModulesBundle?: DepsConfig["skipNodeModulesBundle"];
  alias?: Record<string, string>;
  tsconfig?: string | boolean;
  platform?: "node" | "neutral" | "browser";
  target?: Arrayable<string> | false;
  env?: Record<string, any>;
  envFile?: string;
  envPrefix?: Arrayable<string>;
  define?: TransformOptions["define"];
  shims?: boolean;
  treeshake?: InputOptions["treeshake"];
  loader?: InputOptions["moduleTypes"];
  removeNodeProtocol?: boolean;
  nodeProtocol?: "strip" | boolean;
  checks?: ChecksOptions & {
    legacyCjs?: boolean;
  };
  plugins?: TsdownPluginOption;
  inputOptions?: InputOptions | ((_: InputOptions, _: NormalizedFormat, _: {
    cjsDts: boolean;
  }) => Awaitable<InputOptions | void | null>);
  format?: Arrayable<Format> | Partial<Record<Format, Partial<ResolvedConfig>>>;
  globalName?: OutputOptions["name"];
  outDir?: string;
  write?: BuildOptions["write"];
  sourcemap?: OutputOptions["sourcemap"];
  clean?: boolean | string[];
  minify?: OutputOptions["minify"];
  footer?: ChunkAddon;
  banner?: ChunkAddon;
  unbundle?: boolean;
  root?: string;
  bundle?: boolean;
  fixedExtension?: boolean;
  outExtensions?: OutExtensionFactory;
  hash?: boolean;
  cjsDefault?: boolean;
  outputOptions?: OutputOptions | ((_: OutputOptions, _: NormalizedFormat, _: {
    cjsDts: boolean;
  }) => Awaitable<OutputOptions | void | null>);
  cwd?: string;
  name?: string;
  logLevel?: LogLevel;
  failOnWarn?: boolean | CIOption;
  customLogger?: Logger;
  fromVite?: boolean | "vitest";
  watch?: boolean | Arrayable<string>;
  ignoreWatch?: Arrayable<string | RegExp>;
  devtools?: WithEnabled<DevtoolsOptions>;
  onSuccess?: string | ((_: ResolvedConfig, _: AbortSignal) => Awaitable<void>);
  dts?: WithEnabled<DtsOptions>;
  unused?: WithEnabled<UnusedOptions>;
  publint?: WithEnabled<PublintOptions>;
  attw?: WithEnabled<AttwOptions>;
  report?: WithEnabled<ReportOptions>;
  globImport?: boolean;
  exports?: WithEnabled<ExportsOptions>;
  css?: CssOptions;
  injectStyle?: boolean;
  publicDir?: CopyOptions | CopyOptionsFn;
  copy?: CopyOptions | CopyOptionsFn;
  hooks?: Partial<TsdownHooks> | ((_: Hookable<TsdownHooks>) => Awaitable<void>);
  exe?: WithEnabled<ExeOptions>;
  workspace?: Workspace | Arrayable<string> | true;
}
// #endregion

// #region Types
export type UserConfigExport = Awaitable<Arrayable<UserConfig> | UserConfigFn>;
export type UserConfigFn = (_: InlineConfig, _: {
  ci: boolean;
  rootConfig?: UserConfig;
}) => Awaitable<Arrayable<UserConfig>>;
// #endregion

// #region Functions
export declare function defineConfig(_: UserConfigExport): UserConfigExport;
export declare function mergeConfig(_: InlineConfig, ..._: InlineConfig[]): InlineConfig;
// #endregion