/**
 * Generated by tsnapi — public API snapshot of `tsdown/config` */
// Interfaces
export interface UserConfig {
  entry?: TsdownInputOption;
  deps?: DepsConfig;
  external?: ExternalOption;
  noExternal?: Arrayable<string | RegExp> | NoExternalFn;
  inlineOnly?: Arrayable<string | RegExp> | false;
  skipNodeModulesBundle?: boolean;
  alias?: Record<string, string>;
  tsconfig?: string | boolean;
  platform?: "node" | "neutral" | "browser";
  target?: string | string[] | false;
  env?: Record<string, any>;
  envFile?: string;
  envPrefix?: string | string[];
  define?: Record<string, string>;
  shims?: boolean;
  treeshake?: boolean | TreeshakingOptions;
  loader?: ModuleTypes;
  removeNodeProtocol?: boolean;
  nodeProtocol?: "strip" | boolean;
  checks?: ChecksOptions & {
    legacyCjs?: boolean;
  };
  plugins?: InputOptions["plugins"];
  inputOptions?: InputOptions | ((options: InputOptions, format: NormalizedFormat, context: {
    cjsDts: boolean;
  }) => Awaitable<InputOptions | void | null>);
  format?: Format | Format[] | Partial<Record<Format, Partial<ResolvedConfig>>>;
  globalName?: string;
  outDir?: string;
  write?: boolean;
  sourcemap?: Sourcemap;
  clean?: boolean | string[];
  minify?: boolean | "dce-only" | MinifyOptions;
  footer?: ChunkAddon;
  banner?: ChunkAddon;
  unbundle?: boolean;
  root?: string;
  bundle?: boolean;
  fixedExtension?: boolean;
  outExtensions?: OutExtensionFactory;
  hash?: boolean;
  cjsDefault?: boolean;
  outputOptions?: OutputOptions | ((options: OutputOptions, format: NormalizedFormat, context: {
    cjsDts: boolean;
  }) => Awaitable<OutputOptions | void | null>);
  cwd?: string;
  name?: string;
  logLevel?: LogLevel;
  failOnWarn?: boolean | CIOption;
  customLogger?: Logger;
  fromVite?: boolean | "vitest";
  watch?: boolean | Arrayable<string>;
  ignoreWatch?: Arrayable<string | RegExp>;
  devtools?: WithEnabled<DevtoolsOptions>;
  onSuccess?: string | ((config: ResolvedConfig, signal: AbortSignal) => void | Promise<void>);
  dts?: WithEnabled<DtsOptions>;
  unused?: WithEnabled<UnusedOptions>;
  publint?: WithEnabled<PublintOptions>;
  attw?: WithEnabled<AttwOptions>;
  report?: WithEnabled<ReportOptions>;
  globImport?: boolean;
  exports?: WithEnabled<ExportsOptions>;
  css?: _$_tsdown_css0.CssOptions;
  injectStyle?: boolean;
  publicDir?: CopyOptions | CopyOptionsFn;
  copy?: CopyOptions | CopyOptionsFn;
  hooks?: Partial<TsdownHooks> | ((hooks: Hookable<TsdownHooks>) => Awaitable<void>);
  exe?: WithEnabled<ExeOptions>;
  workspace?: Workspace | Arrayable<string> | true;
}

// Types
export type UserConfigExport = Awaitable<Arrayable<UserConfig> | UserConfigFn>;
export type UserConfigFn = (inlineConfig: InlineConfig, context: {
  ci: boolean;
  rootConfig?: UserConfig;
}) => Awaitable<Arrayable<UserConfig>>;

// Functions
export declare function defineConfig(_: UserConfigExport): UserConfigExport;
export declare function mergeConfig(_: InlineConfig, ..._: InlineConfig[]): InlineConfig;