/**
 * Generated by tsnapi — public API snapshot of `tsdown/internal` */
// Interfaces
export interface Logger {
  level: LogLevel;
  options?: LoggerOptions;
  info: (...args: any[]) => void;
  warn: (...args: any[]) => void;
  warnOnce: (...args: any[]) => void;
  error: (...args: any[]) => void;
  success: (...args: any[]) => void;
  clearScreen: (type: LogType) => void;
}

// Types
export type MarkPartial<T, K extends keyof T> = Omit<Required<T>, K> & Partial<Pick<T, K>>;
export type Overwrite<T, U> = Omit<T, keyof U> & U;

// Functions
export declare function expandBaselineTarget(_: string[]): string[];
export declare function fsExists(_: string): Promise<boolean>;
export declare function fsRemove(_: string): Promise<void>;
export declare function importWithError<T>(_: string): Promise<T>;
export declare function resolveComma<T extends string>(_: T[]): T[];
export declare function toArray<T>(_: T | T[] | null | undefined, _?: T): T[];