/**
 * Generated by tsnapi — public API snapshot of `tsdown/plugins` */
// Interfaces
export interface TsdownConfigEnv {
  watch: boolean;
  inlineConfig: InlineConfig;
  cwd: string;
}
export interface TsdownPlugin<A = any> extends Plugin<A> {
  tsdownConfig?: (_: UserConfig, _: TsdownConfigEnv) => Awaitable<UserConfig | Partial<UserConfig> | void | null>;
  tsdownConfigResolved?: (_: ResolvedConfig) => Awaitable<void>;
}

// Functions
export declare function DepsPlugin({
  pkg,
  deps: {
    alwaysBundle,
    onlyBundle,
    skipNodeModulesBundle
  },
  logger,
  nameLabel
}: ResolvedConfig, _: TsdownBundle): Plugin;
export declare function flattenPlugins(_: RolldownPluginOption): Promise<Plugin[]>;
export declare function NodeProtocolPlugin(_: "strip" | true): Plugin;
export declare function ReportPlugin(_: ResolvedConfig, _?: boolean, _?: boolean): Plugin;
export declare function ShebangPlugin(_: Logger, _: string, _?: string, _?: boolean): Plugin;
export declare function WatchPlugin(_: string[], {
  config,
  chunks
}: TsdownBundle): Plugin;