/**
 * Generated by tsnapi — public API snapshot of `tsdown/plugins` */
// Functions
export declare function DepsPlugin({
  pkg,
  deps: {
    alwaysBundle,
    onlyBundle,
    skipNodeModulesBundle
  },
  logger,
  nameLabel
}: ResolvedConfig, _: TsdownBundle): Plugin;
export declare function NodeProtocolPlugin(_: "strip" | true): Plugin;
export declare function ReportPlugin(_: ResolvedConfig, _?: boolean, _?: boolean): Plugin;
export declare function ShebangPlugin(_: Logger, _: string, _?: string, _?: boolean): Plugin;
export declare function WatchPlugin(_: string[], {
  config,
  chunks
}: TsdownBundle): Plugin;