name: Deploy

permissions: {}

on:
  push:
    branches: [release]
    paths:
      - docs/**
      - src/**
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - tsconfig.json
      - .github/workflows/src/deploy.yml
      - .github/workflows/deploy.yml

jobs:
  deploy-void:
    name: Deploy to Void
    if: github.repository == 'rolldown/tsdown'
    runs-on: ubuntu-latest
    environment: void
    permissions:
      id-token: write
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@main

      - name: Generate Docs
        run: pnpm run docs:generate

      - name: Deploy to Void
        run: |
          pnpm -C docs run void connect "$VOID_API_URL" --no-login
          pnpm -C docs run void deploy
        env:
          VOID_API_URL: https://api.void.cloud
          VOID_PROJECT: tsdown
