name: Unit Test

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    uses: sxzz/workflows/.github/workflows/unit-test.yml@v1
    with:
      node-versions: '22,24,25'
      os-matrix: '"ubuntu-latest", "windows-latest"'

  test_25_8_0:
    uses: sxzz/workflows/.github/workflows/unit-test.yml@v1
    with:
      node-versions: '25.8.0'
      os-matrix: '"ubuntu-latest", "windows-latest"'
      test: "TSDOWN_TEST_BUILTIN_SEA=1 pnpm test run tests/exe.test.ts"

  test_24_14_0:
    uses: sxzz/workflows/.github/workflows/unit-test.yml@v1
    with:
      node-versions: '24.14.0'
      os-matrix: '"ubuntu-latest", "windows-latest"'
      test: "TSDOWN_TEST_BUILTIN_SEA=1 pnpm test run tests/exe.test.ts"

  test_22_22_0:
    uses: sxzz/workflows/.github/workflows/unit-test.yml@v1
    with:
      node-versions: '22.22.0'
      os-matrix: '"ubuntu-latest", "windows-latest"'
      test: "TSDOWN_TEST_BUILTIN_SEA=1 pnpm test run tests/exe.test.ts"
